### ISSUE TITLE
The iod features can not concat with the bottom-up features

### ISSUE THREAD

**Issue by Gary-code** [CUMTGG/CIIC#6]
Congratulations on the paper accepted by CVPR. Here is a question, the iod features can not concatenate with the bottom-up features, because the object num seems not equal? After carefully reading the paper, I think each object detected by faster-RCNN has an unbiased feature. Looking forward to your reply.

**Comment by pandawynn** [comment]
> Congratulations on the paper accepted by CVPR. Here is a question, the iod features can not concatenate with the bottom-up features, because the object num seems not equal? After carefully reading the paper, I think each object detected by faster-RCNN has an unbiased feature. Looking forward to your reply.

您好，请问您iod 特征在哪里下载的啊，是作者给的那个失效的百度云链接吗? :)

**Comment by Githubdzp** [comment]
> Congratulations on the paper accepted by CVPR. Here is a question, the iod features can not concatenate with the bottom-up features, because the object num seems not equal? After carefully reading the paper, I think each object detected by faster-RCNN has an unbiased feature. Looking forward to your reply.

Hello, do you have the cloud disk file shared by the author?
